package Exception;

import java.io.IOException;

public class Exception2 extends Exception1 {
	void activity() throws IOException
	{
		System.out.println("Inside program 2 activity");
	}
}
